<a href="https://colab.research.google.com/github/crazycodersdev/DATA-MINING/blob/main/Case_Study_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Case Study Scenario: Student Performance and Demographics Analysis**

**Scenario Overview:**
You are working as a data analyst for a university. The university wants to understand the relationship between various factors such as student demographics, study habits, and performance in different subjects. The university’s goal is to improve the overall performance of students by identifying trends and patterns in the data. You’ve been given a dataset containing information about students' demographics, study time, school performance, and absenteeism.

**Business Problem:**

The university is particularly interested in the following areas:
How does the gender of students impact their academic performance?
What is the relationship between study time and performance?
Are there any patterns between school type (private or public) and student grades?
Does absenteeism have an impact on student performance?


You are tasked with performing Data Transformation on the dataset, which involves encoding categorical variables, creating new derived features (like age), and aggregating data to extract meaningful insights.

#Transformations to Perform:
You will perform the following data transformations to prepare the dataset for analysis:

#Data Encoding:

Convert the Gender column (Male/Female) into numeric values using One-Hot Encoding.
Convert the School Type column (Public/Private) into numeric values using One-Hot Encoding.
Convert the Grade column (A, B, C) into numeric values using Label Encoding (A = 1, B = 2, C = 3).

#Create New Derived Columns:

Create a new column Age by calculating the student’s age from the Date of Birth column.
Create a new column Total Score by summing the Math, Reading, and Writing scores.

#Aggregation and Grouping:

Calculate the average score (Math, Reading, Writing) for each Gender and School Type (Public/Private).
Use a pivot table to summarize the data by Grade and School Type to see the average performance of students based on these categories.
Step-by-Step Instructions:


#Data Preprocessing and Transformation:

One-Hot Encoding: Use pd.get_dummies() to transform categorical columns (Gender, School Type) into separate numeric columns.

Label Encoding: Map Grade values to numerical values using map() function (A = 1, B = 2, C = 3).

#Age Calculation:

Use the Date of Birth column to calculate the Age of each student by subtracting the birth year from the current year.

#Total Score Calculation:

Sum the Math Score, Reading Score, and Writing Score columns to create a new Total Score column.

#Group and Aggregate Data:

Group by Gender and School Type: Use groupby() to calculate the mean of the scores for each gender and school type.

# Pivot Table:

Create a pivot table to show the average scores of students for each grade and school type.



---

**Steps to Perform Data Transformation:**

Data Encoding:

One-hot encoding: Convert categorical variables (like "Gender" and "School Type") into numeric columns.
Label Encoding: Convert the "Grade" column (A, B, C, etc.) into numeric values.

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/university_student.csv')

In [6]:
df

,Student ID,Gender,Date of Birth,Study Time,Grade,School Type,Absences,Math Score,Reading Score,Writing Score
0,1,Male,1996-12-03,11,D,Public,2,72,91,69
1,2,Female,2001-09-15,5,D,Private,0,66,58,62
2,3,Male,2002-08-09,8,A,Private,2,75,99,77
3,4,Male,1999-04-29,8,A,Private,3,57,76,97
4,5,Male,1995-06-11,9,B,Private,1,78,51,78
...,...,...,...,...,...,...,...,...,...,...
95,96,Female,2004-12-04,8,C,Public,1,87,85,88
96,97,Female,2003-01-18,7,B,Private,4,56,76,87
97,98,Female,1999-01-24,14,A,Private,2,95,66,83
98,99,Female,2005-04-20,7,B,Private,1,62,58,87
99,100,Male,2004-12-25,7,B,Private,2,89,82,99

In [7]:
df.isnull().sum()

Student ID       0
Gender           0
Date of Birth    0
Study Time       0
Grade            0
School Type      0
Absences         0
Math Score       0
Reading Score    0
Writing Score    0
dtype: int64

# 1 .One-Hot Encoding for Gender and School Type

In [8]:
df_encoded = pd.get_dummies(df, columns=['Gender', 'School Type'], drop_first=True)

In [9]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,True,True
1,2,2001-09-15,5,D,0,66,58,62,False,False
2,3,2002-08-09,8,A,2,75,99,77,True,False
3,4,1999-04-29,8,A,3,57,76,97,True,False
4,5,1995-06-11,9,B,1,78,51,78,True,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,False,True
96,97,2003-01-18,7,B,4,56,76,87,False,False
97,98,1999-01-24,14,A,2,95,66,83,False,False
98,99,2005-04-20,7,B,1,62,58,87,False,False
99,100,2004-12-25,7,B,2,89,82,99,True,False

In [11]:
df_encoded['Gender_Male']=df_encoded['Gender_Male'].astype(int)

In [12]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,1,True
1,2,2001-09-15,5,D,0,66,58,62,0,False
2,3,2002-08-09,8,A,2,75,99,77,1,False
3,4,1999-04-29,8,A,3,57,76,97,1,False
4,5,1995-06-11,9,B,1,78,51,78,1,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,0,True
96,97,2003-01-18,7,B,4,56,76,87,0,False
97,98,1999-01-24,14,A,2,95,66,83,0,False
98,99,2005-04-20,7,B,1,62,58,87,0,False
99,100,2004-12-25,7,B,2,89,82,99,1,False

In [13]:
df_encoded['School Type_Public']=df_encoded['School Type_Public'].astype(int)

In [15]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,1,1
1,2,2001-09-15,5,D,0,66,58,62,0,0
2,3,2002-08-09,8,A,2,75,99,77,1,0
3,4,1999-04-29,8,A,3,57,76,97,1,0
4,5,1995-06-11,9,B,1,78,51,78,1,0
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,0,1
96,97,2003-01-18,7,B,4,56,76,87,0,0
97,98,1999-01-24,14,A,2,95,66,83,0,0
98,99,2005-04-20,7,B,1,62,58,87,0,0
99,100,2004-12-25,7,B,2,89,82,99,1,0

# 2. Label Encoding for Grade using LabelEncoder from sklearn

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label_encoder = LabelEncoder()

In [19]:
df_encoded['Grade'] = label_encoder.fit_transform(df_encoded['Grade'])

In [21]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,3,2,72,91,69,1,1
1,2,2001-09-15,5,3,0,66,58,62,0,0
2,3,2002-08-09,8,0,2,75,99,77,1,0
3,4,1999-04-29,8,0,3,57,76,97,1,0
4,5,1995-06-11,9,1,1,78,51,78,1,0
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,2,1,87,85,88,0,1
96,97,2003-01-18,7,1,4,56,76,87,0,0
97,98,1999-01-24,14,0,2,95,66,83,0,0
98,99,2005-04-20,7,1,1,62,58,87,0,0
99,100,2004-12-25,7,1,2,89,82,99,1,0

In [22]:
df

,Student ID,Gender,Date of Birth,Study Time,Grade,School Type,Absences,Math Score,Reading Score,Writing Score
0,1,Male,1996-12-03,11,D,Public,2,72,91,69
1,2,Female,2001-09-15,5,D,Private,0,66,58,62
2,3,Male,2002-08-09,8,A,Private,2,75,99,77
3,4,Male,1999-04-29,8,A,Private,3,57,76,97
4,5,Male,1995-06-11,9,B,Private,1,78,51,78
...,...,...,...,...,...,...,...,...,...,...
95,96,Female,2004-12-04,8,C,Public,1,87,85,88
96,97,Female,2003-01-18,7,B,Private,4,56,76,87
97,98,Female,1999-01-24,14,A,Private,2,95,66,83
98,99,Female,2005-04-20,7,B,Private,1,62,58,87
99,100,Male,2004-12-25,7,B,Private,2,89,82,99

# 3. Create New Derived Columns (Age and Total Score)

In [23]:
df_encoded['Date of Birth'] = pd.to_datetime(df_encoded['Date of Birth'])

In [24]:
df_encoded['Age'] = pd.to_datetime('today').year - df_encoded['Date of Birth'].dt.year

In [25]:
df_encoded['Total Score'] = df_encoded['Math Score'] + df_encoded['Reading Score'] + df_encoded['Writing Score']

In [26]:
df_encoded

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public,Age,Total Score
0,1,1996-12-03,11,3,2,72,91,69,1,1,29,232
1,2,2001-09-15,5,3,0,66,58,62,0,0,24,186
2,3,2002-08-09,8,0,2,75,99,77,1,0,23,251
3,4,1999-04-29,8,0,3,57,76,97,1,0,26,230
4,5,1995-06-11,9,1,1,78,51,78,1,0,30,207
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,2,1,87,85,88,0,1,21,260
96,97,2003-01-18,7,1,4,56,76,87,0,0,22,219
97,98,1999-01-24,14,0,2,95,66,83,0,0,26,244
98,99,2005-04-20,7,1,1,62,58,87,0,0,20,207
99,100,2004-12-25,7,1,2,89,82,99,1,0,21,270

# 4. Group and Aggregate Data

In [28]:
grouped_data = df_encoded.groupby(['Gender_Male', 'School Type_Public']).agg({'Math Score': 'mean', 'Reading Score': 'mean', 'Writing Score': 'mean'})

In [29]:
grouped_data

                                Math Score  Reading Score  Writing Score
Gender_Male School Type_Public
0           0                    80.314286      71.742857      73.600000
            1                    75.761905      78.285714      77.047619
1           0                    70.000000      74.875000      73.791667
            1                    76.050000      74.250000      76.000000

In [32]:
pivot_data = df_encoded.pivot_table(values=['Math Score', 'Reading Score', 'Writing Score'], index=['Grade'], columns=['School Type_Public'], aggfunc='mean')

In [33]:
pivot_data

                   Math Score            Reading Score             \
School Type_Public          0          1             0          1
Grade
0                   79.117647  77.545455     73.647059  80.181818
1                   78.555556  72.000000     66.222222  69.000000
2                   73.111111  78.000000     77.111111  77.833333
3                   77.333333  74.454545     74.416667  75.181818
4                   71.083333  72.000000     72.750000  69.750000

                   Writing Score
School Type_Public             0          1
Grade
0                      76.882353  79.272727
1                      72.444444  69.333333
2                      76.333333  77.500000
3                      77.666667  75.363636
4                      64.083333  74.750000

In [34]:
print("Transformed Data:")
print(df_encoded)

Transformed Data:
    Student ID Date of Birth  Study Time  Grade  Absences  Math Score  \
0            1    1996-12-03          11      3         2          72
1            2    2001-09-15           5      3         0          66
2            3    2002-08-09           8      0         2          75
3            4    1999-04-29           8      0         3          57
4            5    1995-06-11           9      1         1          78
..         ...           ...         ...    ...       ...         ...
95          96    2004-12-04           8      2         1          87
96          97    2003-01-18           7      1         4          56
97          98    1999-01-24          14      0         2          95
98          99    2005-04-20           7      1         1          62
99         100    2004-12-25           7      1         2          89

    Reading Score  Writing Score  Gender_Male  School Type_Public  Age  \
0              91             69            1                   1   29
1              58             62            0                   0   24
2              99             77            1                   0   23
3              76             97            1                   0   26
4              51             78            1                   0   30
..            ...            ...          ...                 ...  ...
95             85             88            0                   1   21
96             76             87            0                   0   22
97             66             83            0                   0   26
98             58             87            0                   0   20
99             82             99            1                   0   21

    Total Score
0           232
1           186
2           251
3           230
4           207
..          ...
95          260
96          219
97          244
98          207
99          270

[100 rows x 12 columns]

In [35]:
print("\nGrouped Data:")
print(grouped_data)

Grouped Data:
                                Math Score  Reading Score  Writing Score
Gender_Male School Type_Public
0           0                    80.314286      71.742857      73.600000
            1                    75.761905      78.285714      77.047619
1           0                    70.000000      74.875000      73.791667
            1                    76.050000      74.250000      76.000000

In [36]:
print("\nPivot Table Data:")
print(pivot_data)

Pivot Table Data:
                   Math Score            Reading Score             \
School Type_Public          0          1             0          1
Grade
0                   79.117647  77.545455     73.647059  80.181818
1                   78.555556  72.000000     66.222222  69.000000
2                   73.111111  78.000000     77.111111  77.833333
3                   77.333333  74.454545     74.416667  75.181818
4                   71.083333  72.000000     72.750000  69.750000

                   Writing Score
School Type_Public             0          1
Grade
0                      76.882353  79.272727
1                      72.444444  69.333333
2                      76.333333  77.500000
3                      77.666667  75.363636
4                      64.083333  74.750000